

/****** Object:  Table [dbo].[Osoba]    Script Date: 12/29/2019 2:06:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Osoba](
	[Ime] [varchar](255) NOT NULL,
	[Prezime] [varchar](255) NOT NULL,
	[Mobilni] [varchar](255) NOT NULL,
	[Sifra] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Sifra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


