
/****** Object:  Table [dbo].[TipKursa]    Script Date: 12/29/2019 2:06:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TipKursa](
	[IDTipa] [int] NOT NULL,
	[NazivTipa] [nchar](255) NULL,
 CONSTRAINT [PK_TipKursa] PRIMARY KEY CLUSTERED 
(
	[IDTipa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


